
version: 2.1

jobs:
  job1:
    docker:
      - image: circleci/node:15.1
    steps:
      - checkout
      - run:
          name: "save output"
          command: "echo Mother Fucker"

workflows:
  default:
    jobs:
      - job1
