
version: 2.1

jobs:

  configure_infrastructure: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints: ["b0:2e:85:34:a9:2e:b8:10:4a:9c:d0:02:44:f9:18:54"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            apt install ansible
      - run:
          name: Configure server
          command: |
            chmod 400 clavis.pem
            ansible-playbook -i inventory.txt main.yml --private-key clavis.pem
#            ansible-playbook main.yml -i inventory --private-key clavis.pem\

workflows:
  default:
    jobs:
      - configure_infrastructure
