
version: 2.1

jobs:

  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        # - run:
        #     name: Create Cloudformation Stack
        #     command: |
        #       aws cloudformation deploy \
        #         --template-file template.yml \
        #         --stack-name pipelino-${CIRCLE_WORKFLOW_ID:0:5} \
        #         --region us-east-1
        # - run:
        #     name: Add to inventory
        #     command: |
        #       aws ec2 describe-instances \
        #       --query 'Reservations[*].Instances[*].PublicIpAddress' \
        #       --output text >> inventory
        #       cat inventory
        # - save_cache:
        #     paths:
        #       - inventory
        #     key: inventory-{{ checksum "inventory" }}

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - inventory-{{ checksum "inventory" }}
      #       - inventory-
      - add_ssh_keys:
          fingerprints: ["33:f7:63:d3:a0:47:34:e9:2a:20:3d:70:d3:05:c2:10"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml

workflows:
  default:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires: [create_infrastructure]
